name: "Test"
on: [push]
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-18.04
    container: ubuntu:14.04
    steps:
      - id: check
        run: |
          sudo apt install software-properties-common
          sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
