name: "Test"
on: [push]
jobs:
  setup:
    name: "Setup"
    runs-on: macos-10.15
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: exec
        run: |
          g++ main.cpp && ./a.out
