name: "Test"
on: [push]
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-18.04
    container: ubuntu:14.04
    steps:
      - id: setup_env
        run: |
          sudo apt install -y software-properties-common
          sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
          sudo apt update
          sudo apt install wget
          wget https://github.com/Kitware/CMake/releases/download/v3.18.0/cmake-3.18.0-Linux-x86_64.sh
          chmod a+x cmake-3.18.0-Linux-x86_64.sh
          ./cmake-3.18.0-Linux-x86_64.sh --prefix="$HOME/opt/cmake" --skip-license
          echo "::set-env PATH=$HOME/opt/cmake/bin:$PATH"
          echo "::set-env CMAKE_ROOT=$HOME/opt/cmake/share/cmake-3.18"
      - id: build
        run: cmake --version
