name: "Test"
on: [push]
jobs:
  setup:
    name: "Setup"
    runs-on: windows-2016
    steps:
      - id: setup
        run: |
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\;%path%"
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\;%path%"
          PATH="C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%"
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\\MSBuild\15.0\bin;%path%"
          PATH="C:\Program Files (x86)\Windows Kits\10\bin\x86;%path%"
          PATH="C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86;%path%"
          PATH="C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;%path%"
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;%path%"
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools;%path%"
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Roslyn;%path%"
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;%path%"
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;%path%"
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCPackages;%path%"
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86;%path%"
          PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;%path%"
          PATH="C:\Windows\System32\;%path%"
          where msbuild
          where cmake
          where cl
        shell: cmd
      - id: check
        run: msbuild /version
