name: "Test"
on: [push]
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-18.04
    container: ubuntu:14.04
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: setup_env
        run: |
          pwd
          echo $HOME
          ls
      - id: build
        run: cmake --version
