name: "Test"
on: [push]
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{GITHUB_REF}}-ccache
      - id: install_deps
        run: |
          sudo apt install ccache
          export PATH="/usr/lib/ccache:$PATH"
          export CCACHE_LOGFILE=ccache-log.txt
      - id: build
        run: g++ main.cpp
      - id: upload_log
        uses: actions/upload-artifact@v2
        with:
          path: ccache-log.txt
