name: "Test"
on: [push]
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{github.ref}}-ccache-${{github.sha}}
          restore-key: ${{github.ref}}-ccache-
      - id: install_deps
        run: |
          sudo apt install ccache
          echo "::set-env name=PATH::/usr/lib/ccache:$PATH"
          echo "::set-env name=CCACHE_LOGFILE::ccache-log.txt"
      - id: build
        run: env && which g++ && g++ -c main.cpp
      - id: upload_log
        uses: actions/upload-artifact@v2
        with:
          path: ccache-log.txt
