name: "Test"
on: [push, pull_request, workflow_dispatch]
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-18.04
    container: ubuntu:20.04
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ubuntu-20.04-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ubuntu-20.04-${{github.ref}}-
            ubuntu-20.04-refs/heads/master-
      - id: install_deps
        run: |
          apt update
          apt install ccache
          which ccache
          cmake --version
          echo "::set-env name=PATH::/usr/lib/ccache:$PATH"
      - id: build
        run: g++ -c main.cpp
