name: "Test"
on: [push, pull_request, workflow_dispatch]
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-18.04
    container: ubuntu:20.04
    timeout-minutes: 2
    steps:
      - id: install_deps
        run: |
          apt update
          apt install -y tzdata
