name: "Test"
on: [push]
jobs:
  setup:
    name: "Setup"
    runs-on: windows-2016
    steps:
      - id: setup
        uses: warrenbuckley/Setup-MSBuild@v1
      - id: check
        run: msbuild /version
