name: "Test"
on: [push]
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-18.04
    container: ubuntu:14.04
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: setup_env
        run: |
          echo "banana" >> hello.txt
      - id: upload
        uses: actions/upload-artifact@v2
        with:
          name: hello_file
          path: hello.txt
