name: "Test"
on: [push]
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-18.04
    container: ubuntu:14.04
    steps:
      - id: check
        run: |
          patch --version
          sudo apt install -y patch
          patch --version
